import type { CommandId } from '@midnite/studio-shared';
import type { IconType } from 'react-icons';
import { GoIssueOpened } from 'react-icons/go';
import { IoIosGitNetwork } from 'react-icons/io';
import {
  LuActivity,
  LuBot,
  LuChevronLeft,
  LuChevronRight,
  LuClapperboard,
  LuClock,
  LuCommand,
  LuCode,
  LuDownload,
  LuFile,
  LuFileSearch,
  LuFolderOpen,
  LuFolderTree,
  LuGitCommitHorizontal,
  LuGlobe,
  LuLink,
  LuLock,
  LuNotebookPen,
  LuPalette,
  LuPanelLeft,
  LuPanelRight,
  LuPlay,
  LuRefreshCw,
  LuRotateCcw,
  LuRotateCw,
  LuSearch,
  LuSend,
  LuServer,
  LuSparkles,
  LuSquareArrowOutUpRight,
  LuSquareTerminal,
  LuTrash2,
  LuUpload,
  LuX,
  LuZap,
  LuZoomIn,
  LuZoomOut,
} from 'react-icons/lu';

/**
 * Command icons mapping every CommandId to a react-icons icon.
 * Imported per-set (`react-icons/lu`) matching repository guidelines.
 */
export const COMMAND_ICONS: Record<CommandId, IconType> = {
  'terminal.toggle': LuSquareTerminal,
  'terminal.toggleHalfMaximized': LuSquareTerminal,
  'terminal.focus': LuSquareTerminal,
  'terminal.new': LuSquareTerminal,
  'terminal.close': LuX,
  'repos.toggle': LuPanelLeft,
  'browser.toggle': LuGlobe,
  'fab.toggle': LuPanelRight,
  'notes.toggle': LuNotebookPen,
  'companion.toggle': LuBot,
  // A link, not a globe: the command is about WHERE a link goes, and every
  // other `browser.*` row already wears the globe.
  'link.toggleTarget': LuLink,
  'browser.openDevServer': LuServer,
  'activity.toggle': LuActivity,
  'browser.newTab': LuGlobe,
  'browser.closeTab': LuGlobe,
  'browser.nextTab': LuGlobe,
  'browser.prevTab': LuGlobe,
  'browser.reopenTab': LuGlobe,
  'panel.back': LuChevronLeft,
  'panel.forward': LuChevronRight,
  'browser.selectTab1': LuGlobe,
  'browser.selectTab2': LuGlobe,
  'browser.selectTab3': LuGlobe,
  'browser.selectTab4': LuGlobe,
  'browser.selectTab5': LuGlobe,
  'browser.selectTab6': LuGlobe,
  'browser.selectTab7': LuGlobe,
  'browser.selectTab8': LuGlobe,
  'browser.selectTab9': LuGlobe,
  // Distinct glyphs, not another globe (Theme G) — a group of seventeen
  // identical globes is unscannable, and these four are exactly the rows
  // that need to read at a glance.
  'browser.find': LuFileSearch,
  'browser.zoomIn': LuZoomIn,
  'browser.zoomOut': LuZoomOut,
  'browser.zoomReset': LuRotateCcw,
  'browser.devtools': LuCode,
  'browser.clearData': LuTrash2,
  'app.zoomIn': LuZoomIn,
  'app.zoomOut': LuZoomOut,
  'app.zoomReset': LuRotateCcw,
  'repo.open': LuFolderOpen,
  'repo.close': LuX,
  'view.refresh': LuRefreshCw,
  'app.reload': LuRotateCw,
  'app.hardReload': LuZap,
  'app.lock': LuLock,
  'app.screensaver': LuClock,
  'view.graph': IoIosGitNetwork,
  'view.files': LuFolderTree,
  'view.issues': GoIssueOpened,
  'graph.focus': IoIosGitNetwork,
  'status.focus': LuGitCommitHorizontal,
  'status.commit': LuGitCommitHorizontal,
  'sync.fetch': LuRefreshCw,
  'sync.pull': LuDownload,
  'sync.push': LuUpload,
  'search.open': LuSearch,
  'op.abort': LuX,
  'op.continue': LuPlay,
  // LuCommand, not LuSearch: `search.open` (Search Everywhere) is what should
  // own the magnifier, and Phase 39 put both of these on the status bar's
  // shortcut rail where the two would otherwise have worn the same glyph.
  'palette.open': LuCommand,
  'palette.files': LuFile,
  'file.save': LuFile,
  'workflow.run': LuPlay,
  'view.video': LuClapperboard,
  'view.apiClient': LuSend,
  'window.detachActive': LuSquareArrowOutUpRight,
  'window.detachTerminal': LuSquareTerminal,
  'window.detachRepos': LuPanelLeft,
  'window.detachFab': LuPanelRight,
  'window.detachBrowser': LuGlobe,
  'window.detachCompanion': LuBot,
  'markdown.presentAsSlides': LuSparkles,
  'theme.select': LuPalette,
  'theme.import': LuUpload,
};
