import type { CommandId } from '@midnite/studio-shared';
import type { IconType } from 'react-icons';
import {
  LuDownload,
  LuFile,
  LuFolderOpen,
  LuGitBranch,
  LuGitCommitHorizontal,
  LuGlobe,
  LuPanelLeft,
  LuPlay,
  LuRefreshCw,
  LuSearch,
  LuSparkles,
  LuSquareTerminal,
  LuUpload,
  LuX,
} from 'react-icons/lu';

/**
 * Command icons mapping every CommandId to a react-icons icon.
 * Imported per-set (`react-icons/lu`) matching repository guidelines.
 */
export const COMMAND_ICONS: Record<CommandId, IconType> = {
  'terminal.toggle': LuSquareTerminal,
  'terminal.toggleHalfMaximized': LuSquareTerminal,
  'terminal.focus': LuSquareTerminal,
  'repos.toggle': LuPanelLeft,
  'browser.toggle': LuGlobe,
  'browser.newTab': LuGlobe,
  'browser.closeTab': LuGlobe,
  'browser.nextTab': LuGlobe,
  'browser.prevTab': LuGlobe,
  'browser.reopenTab': LuGlobe,
  'browser.selectTab1': LuGlobe,
  'browser.selectTab2': LuGlobe,
  'browser.selectTab3': LuGlobe,
  'browser.selectTab4': LuGlobe,
  'browser.selectTab5': LuGlobe,
  'browser.selectTab6': LuGlobe,
  'browser.selectTab7': LuGlobe,
  'browser.selectTab8': LuGlobe,
  'browser.selectTab9': LuGlobe,
  'repo.open': LuFolderOpen,
  'repo.close': LuX,
  'view.refresh': LuRefreshCw,
  'view.graph': LuGitBranch,
  'graph.focus': LuGitBranch,
  'status.focus': LuGitCommitHorizontal,
  'status.commit': LuGitCommitHorizontal,
  'sync.fetch': LuRefreshCw,
  'sync.pull': LuDownload,
  'sync.push': LuUpload,
  'search.open': LuSearch,
  'op.abort': LuX,
  'op.continue': LuPlay,
  'palette.open': LuSearch,
  'palette.files': LuFile,
  'file.save': LuFile,
  'markdown.presentAsSlides': LuSparkles,
};
