import type { WorkflowTemplate } from './types';

/**
 * The Graph Engineering article's fan-out/join pattern applied to research:
 * three independent lanes joined with `allSettled` (a partial fan-out still
 * publishes), a final check that can send a failed draft through a real
 * `repair` step and back around the loop, and — on the happy path — a human
 * gate before anything actually publishes. See
 * `docs/agentic_engineering/Graph Engineering.md`.
 */
export const researchAndPublishTemplate: WorkflowTemplate = {
  id: 'research-and-publish',
  title: 'Research & publish',
  blurb: 'Fan out across three research lanes, join what settled, draft, check, repair on fail, and get a human sign-off before publishing.',
  source: 'Graph Engineering — "Make writes idempotent so a retry does not duplicate side effects."',
  tags: ['fan-out', 'join', 'verify', 'repair', 'gate'],
  workflow: {
    name: 'Research & publish',
    description: 'Research three lanes, join what settled, draft, check, repair on fail, human sign-off, publish.',
    nodes: [
      {
        id: 'note-join',
        label: 'Note',
        x: 0,
        y: -160,
        kind: 'note',
        config: { text: 'Graph Engineering — "A join is worth the wait only when the next node needs the complete set." allSettled here: a lane that failed still lets the rest through.' },
      },
      { id: 'trigger', label: 'Start', x: 0, y: 0, kind: 'trigger', config: { on: 'manual' } },
      {
        id: 'scope',
        label: 'Scope topic',
        x: 220,
        y: 0,
        kind: 'agent',
        config: { agentId: 'claude', prompt: 'Scope the publishing topic — what does this piece need to cover?' },
      },
      {
        id: 'decompose',
        label: 'Decompose',
        x: 440,
        y: 0,
        kind: 'agent',
        config: { agentId: 'claude', prompt: 'Decompose the topic into three research lanes: company sources, papers, expert posts.' },
      },
      {
        id: 'company-sources',
        label: 'Company sources',
        x: 660,
        y: -120,
        kind: 'http',
        config: { method: 'GET', url: '{{demo.baseUrl}}/demo/research/company', headers: {}, params: {}, queryShaped: false },
      },
      {
        id: 'papers',
        label: 'Papers',
        x: 660,
        y: 0,
        kind: 'http',
        config: { method: 'GET', url: '{{demo.baseUrl}}/demo/research/papers', headers: {}, params: {}, queryShaped: false },
      },
      {
        id: 'expert-posts',
        label: 'Expert posts',
        x: 660,
        y: 120,
        kind: 'http',
        config: { method: 'GET', url: '{{demo.baseUrl}}/demo/research/experts', headers: {}, params: {}, queryShaped: false },
      },
      {
        id: 'join',
        label: 'Join (allSettled)',
        x: 880,
        y: 0,
        kind: 'join',
        config: { mode: 'allSettled', inputs: 3 },
      },
      {
        id: 'dedupe',
        label: 'Dedupe',
        x: 1100,
        y: 0,
        kind: 'transform',
        config: { picks: [{ from: 'fulfilled', to: 'items' }] },
      },
      {
        id: 'draft',
        label: 'Draft',
        x: 1320,
        y: 0,
        kind: 'agent',
        config: { agentId: 'claude', prompt: 'Draft the publication from the deduped research.' },
      },
      {
        id: 'final-check',
        label: 'Final check',
        x: 1540,
        y: 0,
        kind: 'verify',
        config: { check: 'agent', agentId: 'codex', prompt: 'Check the draft for accuracy and completeness. Reply ok if it is publishable, fail otherwise.' },
      },
      {
        id: 'repair',
        label: 'Repair',
        x: 1540,
        y: 160,
        kind: 'agent',
        config: { agentId: 'claude', prompt: "Revise the draft per the final check's feedback." },
      },
      {
        id: 'gate',
        label: 'Sign off',
        x: 1760,
        y: 0,
        kind: 'gate',
        config: { title: 'Approve publication', instructions: 'Review the draft before it goes out.', onTimeout: 'reject' },
      },
      {
        id: 'note-idempotent',
        label: 'Note',
        x: 1980,
        y: -160,
        kind: 'note',
        config: { text: 'Graph Engineering — "Make writes idempotent so a retry does not duplicate side effects."' },
      },
      {
        id: 'publish',
        label: 'Publish',
        x: 1980,
        y: 0,
        kind: 'http',
        config: {
          method: 'POST',
          url: '{{demo.baseUrl}}/demo/echo',
          headers: {},
          params: {},
          queryShaped: false,
          body: '{{draft.output}}',
          idempotent: true,
        },
      },
    ],
    edges: [
      { id: 'e-trigger-scope', from: 'trigger', to: 'scope' },
      { id: 'e-scope-decompose', from: 'scope', to: 'decompose' },
      { id: 'e-decompose-company', from: 'decompose', to: 'company-sources' },
      { id: 'e-decompose-papers', from: 'decompose', to: 'papers' },
      { id: 'e-decompose-experts', from: 'decompose', to: 'expert-posts' },
      { id: 'e-company-join', from: 'company-sources', to: 'join', toPort: 'in-1' },
      { id: 'e-papers-join', from: 'papers', to: 'join', toPort: 'in-2' },
      { id: 'e-experts-join', from: 'expert-posts', to: 'join', toPort: 'in-3' },
      { id: 'e-join-dedupe', from: 'join', to: 'dedupe' },
      { id: 'e-dedupe-draft', from: 'dedupe', to: 'draft' },
      { id: 'e-draft-check', from: 'draft', to: 'final-check' },
      { id: 'e-check-gate', from: 'final-check', to: 'gate', fromPort: 'pass', kind: 'conditional' },
      { id: 'e-check-repair', from: 'final-check', to: 'repair', fromPort: 'fail', kind: 'conditional' },
      {
        id: 'e-repair-loop',
        from: 'repair',
        to: 'draft',
        kind: 'loop',
        loop: { maxIterations: 3, budgetMs: 3_600_000 },
      },
      { id: 'e-repair-gate', from: 'repair', to: 'gate', fromPort: 'exhausted' },
      { id: 'e-gate-publish', from: 'gate', to: 'publish', fromPort: 'approved', kind: 'conditional' },
    ],
  },
};
