import { existsSync } from 'node:fs';
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Readable } from 'node:stream';

import { failure, ok, type GitOpResult } from '@midnite/studio-shared';
import bz2 from 'unbzip2-stream';

// `sherpa-onnx-node` is loaded lazily, not imported here — see
// `loadSherpaOnnx()` below and `inproc-pty.ts`'s identical `loadNodePty()`,
// the precedent this mirrors line for line.
type SherpaOnnxModule = typeof import('sherpa-onnx-node');
type OfflineTtsInstance = InstanceType<SherpaOnnxModule['OfflineTts']>;

/**
 * The local voice engine (Phase 80 Theme C).
 *
 * `speechSynthesis` sounds robotic and was never evaluated against an
 * alternative (Finding 4). This is that alternative: `sherpa-onnx-node`
 * running a Piper VITS voice, entirely in main — the phase doc's TTS
 * comparison table is the record of why this engine and not `kokoro-js`,
 * `@lobehub/tts` or Piper's own now-GPL binary directly.
 *
 * **Follows the `node-pty` precedent exactly** (`docs/INITIAL_PLAN.md:27,147`):
 * a native module, main-process-only, one Electron ABI, and "a lazy fail-soft
 * require degrades to unavailable, not a crash." Three ways this can fail, and
 * all three answer `{ok:false}` rather than throw across the IPC boundary:
 *
 * 1. **The native module itself won't load** — an unsupported platform, or a
 *    missing prebuilt binary. `require('sherpa-onnx-node')` throws
 *    synchronously the moment the platform binary is missing (`addon.js`'s own
 *    fallback message) — a *static* top-level import of it would crash main at
 *    boot on such a platform, so `loadSherpaOnnx()` below calls it lazily
 *    inside a `try`/`catch`, exactly as `inproc-pty.ts`'s `loadNodePty()`
 *    already does for `node-pty` (generalised here to take the loader as a
 *    dependency, since a native module's `require()` is one of the few things
 *    in this codebase a test genuinely cannot swap by mocking the import — it
 *    reaches past the test runner's module graph to Node's real loader). A
 *    failure here is **sticky** for the process's lifetime — retrying a
 *    missing binary on every utterance is pointless work.
 * 2. **The voice model hasn't been provisioned yet.** Downloaded once, lazily,
 *    on first use, into `app.getPath('userData')/companion-voice/` — never
 *    into the app bundle or the repo (the phase's own guardrail). Unlike a
 *    missing native module, a provisioning failure (offline, a flaky mirror)
 *    is treated as **transient**: the next utterance tries again rather than
 *    being permanently silenced by one bad network blip.
 * 3. **Synthesis itself throws** for a given piece of text — reported as a
 *    per-call failure, the model stays loaded for the next attempt.
 *
 * `speaker.ts` on the renderer side treats every `{ok:false}` here identically:
 * fall back to `speechSynthesis` for that utterance. The companion is never
 * left mute because a native module didn't load.
 *
 * **The voice: `en_US-joe-medium`, not the more commonly-demoed `lessac`.**
 * Both are ~61 MB Piper `medium`-quality voices with identical architecture,
 * but `joe`'s own model card licenses its training data CC0 ("public
 * domain") — the cleanest terms of any voice in `rhasspy/piper-voices`, where
 * `lessac`'s card merely links an external Blizzard-2013 licence page that
 * this build did not chase down. The phase's own guardrail is "verify the
 * specific voice's own model card licence before shipping it," and `joe`'s
 * needed no further verification.
 *
 * **Provisioning source: sherpa-onnx's own pre-converted release tarball**,
 * not Piper's raw `.onnx`/`.onnx.json` pair. The pair alone is not enough —
 * sherpa-onnx's VITS loader also needs `tokens.txt` (the phoneme→id table) and
 * `espeak-ng-data` (the phoneme-rule tables the espeak-ng fork compiled into
 * the native binary reads at synthesis time), and both must be cut from the
 * *exact* same conversion as the model or the phoneme ids can silently
 * disagree. `github.com/k2-fsa/sherpa-onnx`'s own `tts-models` release ships
 * all three together, pre-matched, per voice.
 *
 * **A licensing note this build surfaced, for a human to weigh in the PR**:
 * that release tarball's `espeak-ng-data` is generated by, and the native
 * `.dylib` this app depends on statically links, a fork of `espeak-ng`
 * (`csukuangfj/espeak-ng`, see `cmake/espeak-ng-for-piper.cmake` in the
 * sherpa-onnx source) — and `espeak-ng` is **GPL-3.0**, not Apache-2.0. The
 * phase doc's comparison table frames sherpa-onnx as sidestepping Piper's own
 * GPL-3.0 fork "entirely," which is true of Piper's *code* but does not
 * appear to cover this: sherpa-onnx's compiled binary embeds a GPL-3.0
 * component for the same phonemization job Piper needed one for. This was not
 * caught by the phase doc's research and needs a human legal read before this
 * ships to end users — see the PR body's Decisions section.
 */

/** Exported for the test's own assertions about on-disk layout — not part of the public contract. */
export const VOICE_ID = 'en_US-joe-medium';

/** github.com/k2-fsa/sherpa-onnx's `tts-models` release — see the module doc. */
const VOICE_TARBALL_URL = `https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-${VOICE_ID}.tar.bz2`;
/** The tarball's own top-level directory, stripped on extraction. */
const TARBALL_ROOT = `vits-piper-${VOICE_ID}`;

/** Give up on a stalled download rather than hanging the first "Say hello" forever. */
const DOWNLOAD_TIMEOUT_MS = 120_000;

export type CompanionTtsDeps = {
  /** `app.getPath('userData')`, injected so this module carries no `electron` import. */
  directory: string;
  fetchImpl: typeof fetch;
  /**
   * `require('sherpa-onnx-node')` — injected, not called inline, for the same
   * reason everything else here is: a native module's `require()` reaches
   * straight past a test runner's module graph to Node's real loader, so
   * `tts.test.ts` swaps this for a fake rather than trying to mock the
   * package itself.
   */
  loadModule: () => SherpaOnnxModule;
};

function requireSherpaOnnx(): SherpaOnnxModule {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  return require('sherpa-onnx-node') as SherpaOnnxModule;
}

function defaultDeps(directory: string): CompanionTtsDeps {
  return { directory, fetchImpl: fetch, loadModule: requireSherpaOnnx };
}

let configured: CompanionTtsDeps | null = null;
let sherpaOnnx: SherpaOnnxModule | null = null;
let ttsInstance: OfflineTtsInstance | null = null;
/** Sticky once set: a missing native module does not become available mid-run. */
let loadFailure: string | null = null;
/**
 * Which of the two sticky-failure call sites set `loadFailure` — `require()`
 * itself throwing (`loadSherpaOnnx`) versus the constructor/`.generate()`
 * throwing later (`synthesizeSpeech`'s own catch). Both are sticky for the
 * same reason (the module doc above), but `getCompanionTtsStatus` reports
 * them as the distinct reasons `tts-status`'s schema promises rather than
 * collapsing both into "native module missing".
 */
let loadFailureKind: 'native-module-missing' | 'synthesis-error' | null = null;
/** Dedupes a provisioning download racing two utterances that both start cold. */
let provisioning: Promise<GitOpResult<VoicePaths>> | null = null;
/**
 * The last provisioning failure, cleared the moment a fresh attempt starts —
 * unlike `loadFailure` this is NOT sticky: a network blip is retried on the
 * next call automatically (the module doc's point 2), and `getCompanionTtsStatus`
 * uses this to explain a `'failed'` `voice` state without re-triggering a
 * download on every poll.
 */
let provisioningError: string | null = null;

/**
 * `deps.loadModule()`, lazily and fail-soft — called on first synthesis
 * request, never at import time, so an unsupported platform or a missing
 * prebuilt binary degrades this feature to "use `speechSynthesis`" instead of
 * crashing main at boot. The same shape as `inproc-pty.ts`'s `loadNodePty()`,
 * generalised to take its loader as a parameter instead of hard-coding
 * `require()` inline.
 */
function loadSherpaOnnx(deps: CompanionTtsDeps): SherpaOnnxModule | null {
  // Checked first, ahead of the cached module: a constructor/generate throw
  // in `synthesizeSpeech` sets `loadFailure` without clearing `sherpaOnnx`
  // (the load itself did succeed), and that failure must still short-circuit
  // every later call rather than retrying a bad model each time.
  if (loadFailure !== null) return null;
  if (sherpaOnnx) return sherpaOnnx;
  try {
    sherpaOnnx = deps.loadModule();
    return sherpaOnnx;
  } catch (error) {
    loadFailure = error instanceof Error ? error.message : 'sherpa-onnx-node failed to load';
    loadFailureKind = 'native-module-missing';
    return null;
  }
}

/** Injected at boot with `app.getPath('userData')`, beside every other store's wiring. */
export function configureCompanionTts(directory: string): void {
  configured = defaultDeps(directory);
}

export function companionTtsDeps(): CompanionTtsDeps | null {
  return configured;
}

/** Reset module state. Tests only. */
export function resetCompanionTtsForTest(overrides: Partial<CompanionTtsDeps> = {}): void {
  sherpaOnnx = null;
  ttsInstance = null;
  loadFailure = null;
  loadFailureKind = null;
  provisioning = null;
  provisioningError = null;
  configured = overrides.directory !== undefined ? defaultDeps(overrides.directory) : null;
  if (configured) {
    if (overrides.fetchImpl !== undefined) configured.fetchImpl = overrides.fetchImpl;
    if (overrides.loadModule !== undefined) configured.loadModule = overrides.loadModule;
  }
}

type VoicePaths = { modelPath: string; tokensPath: string; dataDir: string };

function voiceDir(directory: string): string {
  return join(directory, 'companion-voice', VOICE_ID);
}

function voicePaths(directory: string): VoicePaths {
  const dir = voiceDir(directory);
  return {
    modelPath: join(dir, `${VOICE_ID}.onnx`),
    tokensPath: join(dir, 'tokens.txt'),
    dataDir: join(dir, 'espeak-ng-data'),
  };
}

function voiceReady(paths: VoicePaths): boolean {
  return (
    existsSync(paths.modelPath) && existsSync(paths.tokensPath) && existsSync(paths.dataDir)
  );
}

/**
 * A minimal reader for the one shape of tar entry the sherpa-onnx release
 * tarball actually contains: USTAR headers, regular files and directories,
 * every name under 100 bytes (the longest in this archive is 69). `tar-stream`
 * pulls a real dependency tree (`streamx`, `bare-fs`, `b4a`) for reading one
 * known-good archive once per install; this is the format itself, in full.
 *
 * `strip` removes the tarball's own root directory (`TARBALL_ROOT`) so the
 * files land directly under this module's `voiceDir()` layout; entries outside
 * `keep` (the model, `tokens.txt`, `espeak-ng-data/`) are skipped — this
 * archive also carries `MODEL_CARD` and the raw Piper `.onnx.json`, neither of
 * which `OfflineTts` reads.
 */
async function extractTar(
  buffer: Buffer,
  destDir: string,
  strip: string,
  keep: (relativeName: string) => boolean,
): Promise<void> {
  let offset = 0;
  while (offset + 512 <= buffer.length) {
    const header = buffer.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) break; // end-of-archive marker
    const rawName = header.toString('utf8', 0, 100).replace(/\0.*$/s, '');
    const sizeField = header.toString('utf8', 124, 136).replace(/\0.*$/s, '').trim();
    const size = sizeField.length > 0 ? parseInt(sizeField, 8) : 0;
    const typeflag = String.fromCharCode(header[156] ?? 0);
    offset += 512;

    const prefix = `${strip}/`;
    const relative = rawName.startsWith(prefix) ? rawName.slice(prefix.length) : null;

    if (relative !== null && relative.length > 0 && keep(relative)) {
      const dest = join(destDir, relative);
      if (typeflag === '5') {
        await mkdir(dest, { recursive: true });
      } else if (typeflag === '0' || typeflag === '\0') {
        await mkdir(join(dest, '..'), { recursive: true });
        await writeFile(dest, buffer.subarray(offset, offset + size));
      }
    }

    offset += Math.ceil(size / 512) * 512;
  }
}

/** Buffer a `ReadableStream<Uint8Array>` (a fetch body) into one `Buffer`. */
async function collectStream(stream: ReadableStream<Uint8Array>): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of Readable.fromWeb(stream as never)) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk as Uint8Array));
  }
  return Buffer.concat(chunks);
}

/** Pipe a buffer through `unbzip2-stream` and collect the decompressed result. */
function bunzip2(compressed: Buffer): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const decompressor = bz2();
    decompressor.on('data', (chunk: Buffer) => chunks.push(chunk));
    decompressor.on('end', () => resolve(Buffer.concat(chunks)));
    decompressor.on('error', reject);
    decompressor.end(compressed);
  });
}

/**
 * Download and extract the voice, into a temp directory first and `rename()`d
 * into place last — so a download killed mid-write (the app quit, the network
 * dropped) never leaves `voiceReady()` reading a half-written model as
 * present. Deduped through the module-level `provisioning` promise: two
 * utterances arriving before the first finishes share one download.
 */
async function ensureVoice(deps: CompanionTtsDeps): Promise<GitOpResult<VoicePaths>> {
  const paths = voicePaths(deps.directory);
  if (voiceReady(paths)) {
    provisioningError = null;
    return ok(paths);
  }

  if (provisioning === null) {
    // Cleared at the start of every fresh attempt, not just on success — a
    // `getCompanionTtsStatus` poll mid-download must not still be reporting
    // the *previous* attempt's failure message.
    provisioningError = null;
    provisioning = (async (): Promise<GitOpResult<VoicePaths>> => {
      const dir = voiceDir(deps.directory);
      const tempDir = `${dir}.download-${Date.now()}`;
      try {
        const response = await deps.fetchImpl(VOICE_TARBALL_URL, {
          signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS),
        });
        if (!response.ok || response.body === null) {
          provisioningError = `Could not download the local voice (HTTP ${response.status}). The companion will keep using the system voice.`;
          return failure(provisioningError);
        }
        const compressed = await collectStream(response.body);
        const archive = await bunzip2(compressed);

        await mkdir(tempDir, { recursive: true });
        await extractTar(
          archive,
          tempDir,
          TARBALL_ROOT,
          (name) =>
            name === `${VOICE_ID}.onnx` || name === 'tokens.txt' || name.startsWith('espeak-ng-data/'),
        );

        await rm(dir, { recursive: true, force: true });
        await rename(tempDir, dir);
        if (voiceReady(paths)) {
          provisioningError = null;
          return ok(paths);
        }
        provisioningError =
          'The downloaded voice was incomplete. The companion will keep using the system voice.';
        return failure(provisioningError);
      } catch (error) {
        await rm(tempDir, { recursive: true, force: true }).catch(() => {});
        provisioningError = `Could not set up the local voice (${error instanceof Error ? error.message : String(error)}). The companion will keep using the system voice.`;
        return failure(provisioningError);
      } finally {
        // Each attempt gets a fresh try — a network blip is not sticky like a
        // missing native module is.
        provisioning = null;
      }
    })();
  }
  return provisioning;
}

function loadTts(module: SherpaOnnxModule, paths: VoicePaths): OfflineTtsInstance {
  return new module.OfflineTts({
    model: {
      vits: { model: paths.modelPath, tokens: paths.tokensPath, dataDir: paths.dataDir },
      numThreads: 1,
      provider: 'cpu',
    },
    maxNumSentences: 1,
  });
}

/**
 * 16-bit PCM mono WAV, matching `stt/index.ts`'s `silentWavClip` — the same
 * "no audio assets, no encoder dependency" shape, over generated rather than
 * silent samples. `decodeAudioData` on the renderer side reads a WAV natively.
 */
function encodeWav(samples: Float32Array, sampleRate: number): Uint8Array {
  const dataBytes = samples.length * 2;
  const buffer = new ArrayBuffer(44 + dataBytes);
  const view = new DataView(buffer);
  const ascii = (offset: number, text: string): void => {
    for (let index = 0; index < text.length; index += 1) view.setUint8(offset + index, text.charCodeAt(index));
  };

  ascii(0, 'RIFF');
  view.setUint32(4, 36 + dataBytes, true);
  ascii(8, 'WAVE');
  ascii(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true);
  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);
  ascii(36, 'data');
  view.setUint32(40, dataBytes, true);

  for (let index = 0; index < samples.length; index += 1) {
    const clamped = Math.max(-1, Math.min(1, samples[index] ?? 0));
    view.setInt16(44 + index * 2, clamped < 0 ? clamped * 0x8000 : clamped * 0x7fff, true);
  }

  return new Uint8Array(buffer);
}

/**
 * Text in, one WAV clip out. Never throws — every failure mode in the module
 * doc above answers `{ok:false}` with a sentence `speaker.ts` never has to
 * show (it falls back silently to `speechSynthesis`), because a native-module
 * or a network failure is not something a user typing to the companion caused.
 */
export async function synthesizeSpeech(
  text: string,
  deps: CompanionTtsDeps | null = configured,
): Promise<GitOpResult<{ audio: Uint8Array; mime: string }>> {
  if (deps === null) {
    return failure('The local voice is not set up yet.');
  }
  const module = loadSherpaOnnx(deps);
  if (module === null) {
    return failure('The local voice engine is unavailable on this machine.');
  }

  const provisioned = await ensureVoice(deps);
  if (!provisioned.ok) return provisioned;

  try {
    if (ttsInstance === null) {
      ttsInstance = loadTts(module, provisioned.value);
    }
    const { samples, sampleRate } = ttsInstance.generate({ text, sid: 0, speed: 1.0 });
    return ok({ audio: encodeWav(samples, sampleRate), mime: 'audio/wav' });
  } catch (error) {
    // A throw from `new OfflineTts(...)` or `.generate()` (a corrupt model on
    // disk, an incompatible native binary) is the "missing binary" case in
    // spirit even when it surfaces later than `require()` — sticky for the
    // same reason.
    loadFailure = error instanceof Error ? error.message : 'sherpa-onnx-node failed';
    loadFailureKind = 'synthesis-error';
    ttsInstance = null;
    return failure(
      `The local voice failed to start (${error instanceof Error ? error.message : String(error)}). The companion will keep using the system voice.`,
    );
  }
}

export type CompanionTtsStatusValue = {
  /** This process's own view of which tier it can currently offer. */
  engine: 'local' | 'system';
  voice: 'idle' | 'downloading' | 'ready' | 'failed';
  reason: 'native-module-missing' | 'download-failed' | 'synthesis-error' | null;
  message: string | null;
};

/**
 * A snapshot of the local engine's health for Settings ▸ Companion ▸ Voice —
 * never throws, never synthesizes anything, and by default never re-attempts
 * a provisioning download that already failed (`retry` forces one).
 *
 * The first call made with the voice not yet on disk — or any call with
 * `retry: true` — kicks off `ensureVoice()` and reports `'downloading'`
 * immediately rather than awaiting the up-to-`DOWNLOAD_TIMEOUT_MS` round
 * trip inline; the caller polls again for `'ready'`/`'failed'`. This is what
 * makes opening the Voice section the moment the one-time download starts,
 * instead of the first "Say hello".
 */
export async function getCompanionTtsStatus(
  retry: boolean,
  deps: CompanionTtsDeps | null = configured,
): Promise<CompanionTtsStatusValue> {
  if (deps === null) {
    return { engine: 'system', voice: 'idle', reason: null, message: null };
  }

  const module = loadSherpaOnnx(deps);
  if (module === null) {
    return {
      engine: 'system',
      voice: 'failed',
      reason: loadFailureKind ?? 'native-module-missing',
      message: loadFailure,
    };
  }

  const paths = voicePaths(deps.directory);
  if (voiceReady(paths)) {
    return { engine: 'local', voice: 'ready', reason: null, message: null };
  }

  if (provisioning !== null) {
    return { engine: 'system', voice: 'downloading', reason: null, message: null };
  }

  if (provisioningError !== null && !retry) {
    return { engine: 'system', voice: 'failed', reason: 'download-failed', message: provisioningError };
  }

  // No attempt yet, or an explicit retry after a prior (transient) failure.
  // Fire-and-forget: `ensureVoice` dedupes concurrent callers on its own via
  // `provisioning`, exactly as two overlapping `synthesizeSpeech` calls do.
  void ensureVoice(deps);
  return { engine: 'system', voice: 'downloading', reason: null, message: null };
}
