import { expect, test, type Page } from '@playwright/test';

import { installShotsBridge, setReducedMotion, setTheme, shotPath } from './shots-helper';

/**
 * Phase 109 Themes C and E — the companion changing its own settings:
 * Settings ▸ Companion's "Try: …" hints, the Undo toast a spoken change
 * raises, and the confirm question a `confirm`-tier change asks first.
 *
 * The toast and the question are driven through the real input bar — the
 * grammar, `act()`, the setter and the announcer all run — rather than by
 * seeding a store, so the frames show what that path actually renders.
 *
 * Run with `MSTUDIO_SHOTS=1`; skipped otherwise, matching every other
 * `*-shots.spec.ts` in this suite.
 */
const OUT = '../../docs/screenshots/p109-ce';

test.skip(!process.env['MSTUDIO_SHOTS'], 'set MSTUDIO_SHOTS=1 to regenerate');
// A cold Vite and a loaded machine make the first navigation slow; these are
// regenerated by hand, so patience costs nothing.
test.setTimeout(240_000);
expect.configure({ timeout: 60_000 });

async function open(page: Page): Promise<void> {
  await page.addInitScript(() => {
    const noop = () => {};
    // A synthesiser that finishes every line at once, so a spoken read-back
    // never holds the turn open waiting for an `end` event.
    Object.defineProperty(window, 'speechSynthesis', {
      configurable: true,
      value: {
        speak: (utterance: { onend?: (() => void) | null }) => setTimeout(() => utterance.onend?.(), 0),
        cancel: noop,
        getVoices: () => [],
        addEventListener: noop,
        removeEventListener: noop,
        speaking: false,
        pending: false,
      },
    });
    try {
      const stored = localStorage.getItem('midnite-studio.ui');
      const persisted = stored ? JSON.parse(stored) : { version: 32 };
      persisted.state = { ...persisted.state, companionEnabled: true };
      localStorage.setItem('midnite-studio.ui', JSON.stringify(persisted));
    } catch {
      /* Unparseable profile — the app discards it too. */
    }
  });
  await installShotsBridge(page, {});
  await page.goto('/');
  await expect(page.getByRole('columnheader', { name: 'Commit message' })).toBeVisible();
  await setReducedMotion(page);
  await setTheme(page, 'dark', { settleMs: 200 });
}

async function openCompanionSettings(page: Page): Promise<void> {
  await page.getByRole('button', { name: 'Settings' }).click();
  // Off the rail: hovering it expands it over the settings nav.
  await page.mouse.move(900, 400);
  await page
    .getByRole('navigation', { name: 'Settings pages' })
    .getByRole('button', { name: 'Companion', exact: true })
    .click();
  await expect(page.getByTestId('companion-enable')).toBeVisible();
}

async function say(page: Page, text: string): Promise<void> {
  const input = page.getByTestId('companion-input');
  await input.fill(text);
  await input.press('Enter');
}

test('Settings ▸ Companion ▸ Voice — "Try: …" hints', async ({ page }) => {
  await open(page);
  await openCompanionSettings(page);
  await expect(page.getByTestId('companion-try-companionVoices.local')).toBeVisible();
  await page.getByTestId('companion-try-companionVolume').scrollIntoViewIfNeeded();
  await page.screenshot({ path: shotPath(OUT, 'companion-voice-try-hints.png') });
});

test('Settings ▸ Companion ▸ Personality — "Try: …" hints', async ({ page }) => {
  await open(page);
  await openCompanionSettings(page);
  await page.getByRole('button', { name: 'Personality', exact: true }).first().click();
  await expect(page.getByTestId('companion-try-companionNames')).toBeVisible();
  await page.getByTestId('companion-try-companionMusicOffer').scrollIntoViewIfNeeded();
  await page.screenshot({ path: shotPath(OUT, 'companion-personality-try-hints.png') });
});

test('"use voice Bella" — the read-back and the Undo toast', async ({ page }) => {
  await open(page);
  await page.keyboard.press('Meta+l');
  await page.keyboard.press('c');
  await expect(page.getByTestId('companion-panel')).toBeVisible();

  await say(page, 'use voice Bella');
  await expect(page.getByText('Local voice set to Bella.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Undo' })).toBeVisible();
  await page.screenshot({ path: shotPath(OUT, 'companion-undo-toast.png') });
});

test('"I\'ll call you Nova" — a confirm-tier change asks first', async ({ page }) => {
  await open(page);
  await page.keyboard.press('Meta+l');
  await page.keyboard.press('c');
  await expect(page.getByTestId('companion-panel')).toBeVisible();

  await say(page, "I'll call you Nova");
  await expect(page.getByTestId('companion-pending-action')).toContainText('Answer to "Nova" from now on?');
  await page.screenshot({ path: shotPath(OUT, 'companion-confirm-setting.png') });
});
