/* GENERATED by scripts/make-loop-icons.mjs — do not edit.
   Source: midnite-studio's own loop-icons.ts and loop-glow.ts, and the
   react-icons build they resolve to. Re-run the script to update. */

/**
 * The six agent loops midnite Studio ships, as the film draws them.
 *
 * Each row carries everything about one loop: the name the film types, the
 * app's own id for it, its colour out of the app's table, and its glyph inlined
 * from `react-icons`. One row rather than four parallel lists, so a loop's
 * colour cannot end up on another loop's icon.
 *
 * `stroked` is the one thing a caller has to respect: Lucide's glyphs are
 * strokes on an unfilled path and the rest are filled shapes, so the colour goes
 * to a different attribute for each. Painting a filled glyph's stroke leaves it
 * black, which on this film's dark stage is nothing at all.
 */
export type LoopIcon = {
  /** What the film types, after the `/`. */
  slug: string;
  /** The app's own loop id — the key into its colour table. */
  id: string;
  /** The loop's colour, from the app's `loop-glow.ts`. */
  colour: string;
  /** True when the glyph is drawn with a stroke rather than a fill. */
  stroked: boolean;
  /** Draw the glyph at `size` px in `colour`. */
  Icon: React.FC<{ size: number; colour: string; opacity?: number }>;
};

export const LOOP_ICONS: readonly LoopIcon[] = [
  {
    slug: "guard",
    id: "guard",
    colour: "#22c55e",
    stroked: true,
    Icon: ({ size, colour, opacity = 1 }) => (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke={colour}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        opacity={opacity}
        aria-hidden
      >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
      <path d="m9 12 2 2 4-4" />
      </svg>
    ),
  },
  {
    slug: "concepts",
    id: "innovate",
    colour: "#06b6d4",
    stroked: false,
    Icon: ({ size, colour, opacity = 1 }) => (
      <svg
        width={size}
        height={size}
        viewBox="0 0 512 512"
        fill={colour}
        
        
        
        
        opacity={opacity}
        aria-hidden
      >
      <path d="M256 25.063c-61.584 61.583-76.97 107.77-76.97 138.562 0 30.792 46.18 46.188 76.97 46.188 30.792 0 76.97-15.396 76.97-46.188S317.583 86.647 256 25.062zM132.72 204.125c-9.21-.108-20.947 1.46-36.72 5.688 11.27 42.062 24.604 49.77 37.938 57.468C147.27 274.98 168.3 269.335 176 256c7.698-13.333 2.053-34.365-11.28-42.063-8.334-4.81-16.654-9.632-32-9.812zm246.56 0c-15.346.18-23.666 5-32 9.813-13.332 7.697-18.978 28.73-11.28 42.062 7.698 13.333 28.73 18.98 42.063 11.28 13.333-7.697 26.667-15.405 37.937-57.467-15.774-4.227-27.51-5.796-36.72-5.688zM256 240.595c-34.01 0-61.594 27.58-61.594 61.593 0 34.01 27.583 61.593 61.594 61.593 34.01 0 61.594-27.58 61.594-61.592S290.01 240.594 256 240.594zm-144.03 60.218c-5.005.098-9.887 1.353-14.47 4C70.833 320.21 38.542 356.625 16 440.75c84.125 22.54 131.833 12.77 158.5-2.625 26.667-15.396 16.896-63.083 1.5-89.75-12.75-22.084-39.923-48.04-64.03-47.563zm286.686 0c-23.76.5-50.147 25.895-62.656 47.562-15.396 26.667-25.167 74.354 1.5 89.75s74.375 25.166 158.5 2.625c-22.54-84.126-54.833-120.54-81.5-135.938-5-2.886-10.36-4.115-15.844-4zM256 394.563c-15.396 0-30.78 15.385-30.78 30.78 0 15.397-.012 30.803 30.78 61.594 30.792-30.792 30.78-46.198 30.78-61.593 0-15.396-15.384-30.78-30.78-30.78z" />
      </svg>
    ),
  },
  {
    slug: "develop",
    id: "automate",
    colour: "#3b82f6",
    stroked: false,
    Icon: ({ size, colour, opacity = 1 }) => (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill={colour}
        
        
        
        
        opacity={opacity}
        aria-hidden
      >
      <path d="M4.823 11.139 11.253 0 1.608 5.57zM1.235 6.646v10.708L4.325 12zM12 23.57l6.43-11.14H5.57zM12 .43 5.57 11.57h12.86zm10.764 16.924V6.646L19.674 12zm.001.862-.374.215-3.215-5.57L12.746 24zm0-12.431L12.745 0l6.431 11.139 3.215-5.57zM1.235 18.216 11.254 24l-6.43-11.138-3.216 5.569z" />
      </svg>
    ),
  },
  {
    slug: "patrol",
    id: "watchdog",
    colour: "#8b5cf6",
    stroked: false,
    Icon: ({ size, colour, opacity = 1 }) => (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill={colour}
        
        
        
        
        opacity={opacity}
        aria-hidden
      >
      <path d="M16.3696 2.5006 12.0006 5 7.6303 7.5006v-5L12.0006 0Zm6.1177 3.499.0028 4.986-8.7282-4.9929 4.3564-2.4923Zm-4.369 9.5085-.0014 4.9972 4.3774-2.5007-.0028-5.018-4.3732-2.502zM7.6274 21.502 12.0006 24l4.369-2.4952v-4.9972zM7.6303 9.5v5.0014l4.3703 2.4992 4.369-2.4937V9.5001l-4.369-2.4993Zm-6.1248 8.5044.0028-5.0055 8.7464 5.0027-4.376 2.5008Zm4.376-14.504L1.5125 6.001l-.0028 4.9985 4.3718 2.502z" />
      </svg>
    ),
  },
  {
    slug: "medic",
    id: "medic",
    colour: "#ef4444",
    stroked: false,
    Icon: ({ size, colour, opacity = 1 }) => (
      <svg
        width={size}
        height={size}
        viewBox="0 0 512 512"
        fill={colour}
        
        
        
        
        opacity={opacity}
        aria-hidden
      >
      <path d="M320.2 243.8l-49.7 99.4c-6 12.1-23.4 11.7-28.9-.6l-56.9-126.3-30 71.7H60.6l182.5 186.5c7.1 7.3 18.6 7.3 25.7 0L451.4 288H342.3l-22.1-44.2zM473.7 73.9l-2.4-2.5c-51.5-52.6-135.8-52.6-187.4 0L256 100l-27.9-28.5c-51.5-52.7-135.9-52.7-187.4 0l-2.4 2.4C-10.4 123.7-12.5 203 31 256h102.4l35.9-86.2c5.4-12.9 23.6-13.2 29.4-.4l58.2 129.3 49-97.9c5.9-11.8 22.7-11.8 28.6 0l27.6 55.2H481c43.5-53 41.4-132.3-7.3-182.1z" />
      </svg>
    ),
  },
  {
    slug: "overhaul",
    id: "overhaul",
    colour: "#f97316",
    stroked: true,
    Icon: ({ size, colour, opacity = 1 }) => (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke={colour}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        opacity={opacity}
        aria-hidden
      >
      <path d="m12 14 4-4" />
      <path d="M3.34 19a10 10 0 1 1 17.32 0" />
      </svg>
    ),
  },
];

/** By the name the film types, because that is what the scene has in hand. */
export const loopBySlug = (slug: string): LoopIcon => {
  const found = LOOP_ICONS.find((loop) => loop.slug === slug);
  if (!found) throw new Error(`no loop named '${slug}'`);
  return found;
};
