import type { StudioPalette } from '../theme-types';

export const vscodeDarkPlus = {
  id: 'vscode-dark-plus',
  label: 'VS Code Dark+',
  appearance: 'dark',
  chrome: {
    '--background': '0 0% 12%',
    '--foreground': '0 0% 83%',
    '--card': '0 0% 15%',
    '--card-foreground': '0 0% 83%',
    '--primary': '207 100% 66%',
    '--primary-foreground': '0 0% 10%',
    '--secondary': '0 0% 20%',
    '--secondary-foreground': '0 0% 83%',
    '--muted': '0 0% 18%',
    '--muted-foreground': '0 0% 60%',
    '--accent': '0 0% 22%',
    '--accent-foreground': '0 0% 90%',
    '--destructive': '0 65% 60%',
    '--destructive-foreground': '0 0% 10%',
    '--success': '105 45% 55%',
    '--success-foreground': '0 0% 10%',
    '--popover': '0 0% 14%',
    '--popover-foreground': '0 0% 83%',
    '--border': '0 0% 27%',
    '--input': '0 0% 27%',
    '--ring': '207 100% 66%',
  },
  terminal: {
    background: '#1e1e1e',
    foreground: '#cccccc',
    cursor: '#cccccc',
    selectionBackground: '#264f78',
    black: '#000000',
    red: '#cd3131',
    green: '#0dbc79',
    yellow: '#e5e510',
    blue: '#2472c8',
    magenta: '#bc3fbc',
    cyan: '#11a8cd',
    white: '#e5e5e5',
    brightBlack: '#666666',
    brightRed: '#f14c4c',
    brightGreen: '#23d18b',
    brightYellow: '#f5f543',
    brightBlue: '#3b8eea',
    brightMagenta: '#d670d6',
    brightCyan: '#29b8db',
    brightWhite: '#e5e5e5',
  },
  editor: {
    base: 'vs-dark',
    rules: [
      { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: '569cd6' },
      { token: 'string', foreground: 'ce9178' },
      { token: 'number', foreground: 'b5cea8' },
      { token: 'type', foreground: '4ec9b0' },
      { token: 'function', foreground: 'dcdcaa' },
      { token: 'variable', foreground: '9cdcfe' },
    ],
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#d4d4d4',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#c6c6c6',
      'editorCursor.foreground': '#aeafad',
      'editor.selectionBackground': '#264f78',
      'editor.lineHighlightBackground': '#2a2a2a',
      'editorGutter.background': '#1e1e1e',
    },
  },
  highlight: 'dark-plus',
} as const satisfies StudioPalette;
