/**
 * The screensaver's vocabulary, and the three-way mode it is keyed off.
 *
 * Lifted out of `screensaver.tsx` unchanged when the landing page (Phase
 * ad hoc, `features/landing/`) became a second host for the same centre
 * stage: the lists are the longest thing in that file and the shortest thing
 * to share, and two copies of ~250 quips is exactly the kind of duplication
 * that drifts silently.
 */

const ACTIVE_WORDS = [
  'loading',
  'combobulating',
  'midnighting',
  'clauding',
  'vibing',
  'crushing it',
  'orchestrating',
  'klapping',
  'thinking',
  'reticulating',
  'computing',
  'conjuring',
  'brewing',
  'percolating',
  'assembling',
  'hydrating',
  'fidgeting',
  'tinkering',
  'wrangling',
  'noodling',
  'cooking',
  'simmering',
  'marinating',
  'hustling',
  'grinding',
  'flowing',
  'syncing',
  'aligning',
  'calibrating',
  'optimising',
  'refactoring',
  'untangling',
  'debugging',
  'parsing',
  'tokenizing',
  'developrogramming',
  'inferring',
  'reasoning',
  'pondering',
  'cogitating',
  'ruminating',
  'scheming',
  'plotting',
  'sketching',
  'drafting',
  'prototyping',
  'iterating',
  'polishing',
  'buffing',
  'tidying',
  'gardening',
  'pruning',
  'harvesting',
  'gathering',
  'mining',
  'navigating',
  'gliding',
  'soaring',
  'rocketing',
  'warping',
  'summoning',
  'kindling',
  'rolling',
  'sparkling',
  'dazzling',
  'flexing',
  'leveling up',
  'powering up',
  'charging up',
  'gearing up',
  'locking in',
  'dialing in',
  'in the zone, don’t look',
  'shipping it, ma bru',
  'making it happen',
  'heads down, hands moving',
  'this is the good part',
  'watch me work',
  'no notes, just vibes',
  'building the dream',
  'deep in the sauce',
  'chasing green checkmarks',
  'one commit at a time',
  'trust the process',
  'locked in, don’t @ me',
  'moving with purpose',
  'sharp sharp, on it',
  'lekker, this is flowing',
  'in my flow state',
  'busy being brilliant',
  'stacking small wins',
  'green lights all the way',
  'zero to merged',
  'compiling greatness',
];

const WAITING_WORDS = [
  'twiddling thumbs',
  'tumbleweeding',
  'watching ice melt',
  'watching grass grow',
  'watching paint dry',
  'counting ceiling tiles',
  'counting sheep',
  'humming elevator music',
  'staring into space',
  'cooling heels',
  'pacing the floor',
  'checking the clock',
  'killing time',
  'biding time',
  'loitering',
  'holding the line',
  'standing by',
  'awaiting orders',
  'awaiting your word',
  'spinning idle',
  'waiting on you, no rush',
  'ready when you say go',
  'need a yes or a no',
  'just say the word',
  'holding, but patiently',
  'paused, not stopped',
  'stuck at the crossroads',
  'give me the green light',
  'awaiting your blessing',
  'is this thing on?',
  'hello? still here...',
  'parked, engine running',
  'waiting for the go-ahead',
  'your call, boss',
  'sharp, just confirm and I go',
  'blocked on a human, classic',
  'staring at the prompt',
  'the suspense is killing me',
  'a decision awaits',
  'so close, just need a yes',
];

const IDLE_WORDS = [
  'anticipating',
  'keen to roll',
  'wanna vibe?',
  'what\'s up?',
  'ready when you are',
  'itching to go',
  'raring to go',
  'champing at the bit',
  'all charged up',
  'fired up',
  'locked and loaded',
  'queue me up',
  'feed me work',
  'point me at it',
  'give me something',
  'what’s next?',
  'tasks please',
  'let’s build',
  'let’s gooo',
  'let’s vibe',
  'ready to rumble',
  'bored already',
  'idle hands',
  'watching the cursor blink',
  'refreshing an empty board',
  'drop a task, any task',
  'I promise I’ll behave',
  'let’s make something',
  'boot me up, coach',
  'ready, willing, and idle',
  'lekker quiet around here',
  'sharp sharp, gimme work',
];

export type Mode = 'active' | 'waiting' | 'idle';

export const WORD_SETS: Record<Mode, string[]> = {
  active: ACTIVE_WORDS,
  waiting: WAITING_WORDS,
  idle: IDLE_WORDS,
};

export const MODE_TINT: Record<Mode, string> = {
  active: 'var(--primary)',
  waiting: '24 95% 53%',
  idle: 'var(--destructive)',
};

export function nextRandomIndex(length: number, current: number): number {
  if (length <= 1) return 0;
  let next = current;
  while (next === current) next = Math.floor(Math.random() * length);
  return next;
}
